# Generated by Django 5.2 on 2025-05-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTypes',
            new_name='PaymentType',
        ),
    ]
