# Generated by Django 5.2 on 2025-05-11 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_in', '0003_alter_tradein_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradein',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+' followed by digits.", regex='^\\+\\d+$')]),
        ),
    ]
