# Generated by Django 5.2 on 2025-05-03 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
        ('delivery_methods', '0001_initial'),
        ('desktops', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+998' and be followed by 9 digits.", regex='^\\+998\\d{9}$')])),
                ('address', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('process', 'Process'), ('cancelled', 'Cancelled'), ('success', 'Success')], default='process', max_length=10)),
                ('delivery_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery_methods.deliverymethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDesktopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('credit_term', models.IntegerField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='credits.credit')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='desktops.desktop')),
                ('edit_product', models.ManyToManyField(blank=True, related_name='desktop_item_orders', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('credit_term', models.IntegerField()),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item_orders', to='credits.credit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
