# Generated by Django 5.2 on 2025-05-13 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_description_ru_alter_new_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
