# Generated by Django 5.2 on 2025-05-11 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+' followed by digits.", regex='^\\+\\d+$')]),
        ),
    ]
