# Generated by Django 5.2 on 2025-05-07 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message="Phone number must start with '+' followed by digits.", regex='^\\+\\d+$')]),
        ),
    ]
