# Generated by Django 5.2 on 2025-05-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attributes', '0001_initial'),
        ('categories', '0001_initial'),
        ('desktop_types', '0001_initial'),
        ('products', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=255)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attributes', models.ManyToManyField(blank=True, related_name='desktops', to='attributes.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desktops', to='categories.category')),
                ('desktop_types', models.ManyToManyField(related_name='desktops', to='desktop_types.desktoptype')),
                ('products', models.ManyToManyField(related_name='desktops', to='products.product')),
                ('statuses', models.ManyToManyField(related_name='desktops', to='statuses.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesktopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='desktops_images/')),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='desktops.desktop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
