# Generated by Django 5.2 on 2025-05-10 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktops', '0002_alter_desktop_description_ru_alter_desktop_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='description_ru',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Поле должно содержать только русские буквы, пробелы или дефис.', regex='^[А-Яа-яЁё0-9\\s\\-.,!?()@#%&*]+$')]),
        ),
        migrations.AlterField(
            model_name='desktop',
            name='name_ru',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Поле должно содержать только русские буквы, пробелы или дефис.', regex='^[А-Яа-яЁё0-9\\s\\-.,!?()@#%&*]+$')]),
        ),
    ]
