# Generated by Django 5.2 on 2025-05-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktops', '0003_alter_desktop_description_ru_alter_desktop_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
