# Generated by Django 5.2 on 2025-05-13 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0003_alter_attribute_type_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
