# Generated by Django 5.2 on 2025-05-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desktops', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('comment_uz', models.TextField(default='No comment')),
                ('comment_ru', models.TextField(default='No comment')),
                ('description_uz', models.TextField(default='No description')),
                ('description_ru', models.TextField(default='No description')),
                ('image', models.ImageField(upload_to='comment_photos/')),
                ('video', models.FileField(upload_to='comment_videos/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesktopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='product_comments_photo/')),
                ('rating', models.IntegerField()),
                ('desktop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='desktops.desktop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='product_comments_photo/')),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
