# Generated by Django 5.2 on 2025-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0004_alter_comment_comment_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(default='No comment', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_uz',
            field=models.TextField(default='No comment', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description_ru',
            field=models.TextField(default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description_uz',
            field=models.TextField(default='No description', null=True),
        ),
    ]
