# Generated by Django 5.2 on 2025-05-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0005_comment_comment_comment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Без комментариев'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(default='Без комментариев', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_uz',
            field=models.TextField(default='Без комментариев', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description_ru',
            field=models.TextField(default='Нет описания', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description_uz',
            field=models.TextField(default='Нет описания', null=True),
        ),
    ]
